"""add email

Revision ID: 296aa6007b84
Revises: a7e5884864ca
Create Date: 2017-10-12 22:26:41.245683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '296aa6007b84'
down_revision = 'a7e5884864ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
