"""add profile

Revision ID: 643b8ff98e96
Revises: ae8f26c9ae0b
Create Date: 2017-10-17 23:17:09.592068

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '643b8ff98e96'
down_revision = 'ae8f26c9ae0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('member_since', sa.DateTime(), nullable=True))
    op.drop_column('users', 'member_sincee')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('member_sincee', mysql.DATETIME(), nullable=True))
    op.drop_column('users', 'member_since')
    # ### end Alembic commands ###
